name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build
        run: |
          echo "Building the project"

      - name: Create source code archive
        run: |
          tar -czvf kalpak.tar.gz .
          sha256sum kalpak.tar.gz > kalpak.tar.gz.sha256

      - name: Create release
        id: create_release
        uses: gh-actions/create-release@v1
        with:
          tag_name: v${{ github.run_number }}
          release_name: "Release ${{ github.run_number }}"
          release_notes: "Automated release for build ${{ github.run_number }}"

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./kalpak.tar.gz
          asset_name: kalpak.tar.gz
          asset_content_type: application/gzip

      - name: Upload checksum file
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./kalpak.tar.gz.sha256
          asset_name: kalpak.tar.gz.sha256
          asset_content_type: text/plain
